import { useMemo, useState, type ReactNode } from 'react'

export type DataTableColumn<T> = { id: string; header: string; cell: (row: T) => ReactNode; sortValue?: (row: T) => string | number; filterValue?: (row: T) => string }

export function DataTable<T extends { id: string }>({ rows, columns, pageSize = 10, onSelectionChange, selectable = true }: { rows: T[]; columns: DataTableColumn<T>[]; pageSize?: number; onSelectionChange?: (rows: T[]) => void; selectable?: boolean }) {
  const [filter, setFilter] = useState('')
  const [sort, setSort] = useState<{ id: string; desc: boolean } | null>(null)
  const [visible, setVisible] = useState(() => new Set(columns.map((column) => column.id)))
  const [selected, setSelected] = useState<Set<string>>(new Set())
  const [page, setPage] = useState(0)
  const shownColumns = columns.filter((column) => visible.has(column.id))
  const filtered = useMemo(() => rows.filter((row) => columns.some((column) => (column.filterValue?.(row) ?? String(column.sortValue?.(row) ?? '')).toLowerCase().includes(filter.toLowerCase()))).sort((left, right) => { if (!sort) return 0; const column = columns.find((item) => item.id === sort.id); const compared = String(column?.sortValue?.(left) ?? '').localeCompare(String(column?.sortValue?.(right) ?? ''), undefined, { numeric: true }); return sort.desc ? -compared : compared }), [rows, columns, filter, sort])
  const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const slice = filtered.slice(Math.min(page, pages - 1) * pageSize, Math.min(page, pages - 1) * pageSize + pageSize)
  function select(id: string) { const next = new Set(selected); next.has(id) ? next.delete(id) : next.add(id); setSelected(next); onSelectionChange?.(rows.filter((row) => next.has(row.id))) }
  return <section className="data-table"><div className="data-table-controls"><input aria-label="Filter rows" placeholder="Filter" value={filter} onChange={(event) => { setFilter(event.target.value); setPage(0) }} /><details><summary>Columns</summary><div>{columns.map((column) => <label key={column.id}><input type="checkbox" checked={visible.has(column.id)} onChange={() => setVisible((current) => { const next = new Set(current); next.has(column.id) ? next.delete(column.id) : next.add(column.id); return next })} /> {column.header}</label>)}</div></details></div><table><thead><tr>{selectable && <th><input aria-label="Select page" type="checkbox" checked={slice.length > 0 && slice.every((row) => selected.has(row.id))} onChange={() => { const next = new Set(selected); const selectPage = !slice.every((row) => next.has(row.id)); slice.forEach((row) => selectPage ? next.add(row.id) : next.delete(row.id)); setSelected(next); onSelectionChange?.(rows.filter((row) => next.has(row.id))) }} /></th>}{shownColumns.map((column) => <th key={column.id}><button onClick={() => setSort((current) => current?.id === column.id ? { id: column.id, desc: !current.desc } : { id: column.id, desc: false })}>{column.header}{sort?.id === column.id ? sort.desc ? ' ↓' : ' ↑' : ''}</button></th>)}</tr></thead><tbody>{slice.map((row) => <tr key={row.id}>{selectable && <td><input aria-label={`Select ${row.id}`} type="checkbox" checked={selected.has(row.id)} onChange={() => select(row.id)} /></td>}{shownColumns.map((column) => <td key={column.id}>{column.cell(row)}</td>)}</tr>)}{slice.length === 0 && <tr><td colSpan={shownColumns.length + (selectable ? 1 : 0)}>No matching records.</td></tr>}</tbody></table><footer><span>{filtered.length} records{selectable ? ` · ${selected.size} selected` : ''}</span><button disabled={page === 0} onClick={() => setPage(page - 1)}>Previous</button><span>Page {Math.min(page + 1, pages)} / {pages}</span><button disabled={page >= pages - 1} onClick={() => setPage(page + 1)}>Next</button></footer></section>
}
