import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Clock3, FileText, Mail, MessageSquare, Phone, Send, UserRound } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { toast } from 'sonner'
import { startExecution, submitExecutionAction } from '../../shared/api/executions'
import { getMasterData } from '../../shared/api/master-data'
import { getSession, type SessionChannelEvent } from '../../shared/api/sessions'
import { getPublishedVersions } from '../../shared/api/workflows'
import { ErrorState, LoadingState } from '../../shared/components/async-state'
import { StatusBadge } from '../../shared/components/status-badge'
import type { Execution } from '../../shared/types/workflow'

type Channel = 'chat' | 'email' | 'call' | 'document'
const channels: Channel[] = ['chat', 'email', 'call', 'document']
const eventLists: Record<Channel, keyof Pick<Awaited<ReturnType<typeof getSession>>, 'chat_inbox' | 'email_inbox' | 'call_state' | 'document_state'>> = { chat: 'chat_inbox', email: 'email_inbox', call: 'call_state', document: 'document_state' }

export function SimulationRunnerPage() {
  const client = useQueryClient()
  const [participantId, setParticipantId] = useState('')
  const [actorId, setActorId] = useState('')
  const [versionId, setVersionId] = useState('')
  const [execution, setExecution] = useState<Execution | null>(null)
  const versions = useQuery({ queryKey: ['published-versions'], queryFn: getPublishedVersions })
  const actors = useQuery({ queryKey: ['master', 'actors'], queryFn: () => getMasterData('actors') })
  const documents = useQuery({ queryKey: ['master', 'documents'], queryFn: () => getMasterData('documents') })
  const session = useQuery({ queryKey: ['session', execution?.session_id], queryFn: () => getSession(execution!.session_id!), enabled: Boolean(execution?.session_id), refetchInterval: execution?.status === 'waiting' || execution?.status === 'running' ? 2_000 : false })
  const start = useMutation({ mutationFn: startExecution, onSuccess: (result) => { setExecution(result); setVersionId(result.workflow_version_id); client.invalidateQueries({ queryKey: ['session', result.session_id] }); toast.success(result.status === 'waiting' ? 'Active simulation resumed.' : 'Simulation started.') }, onError: () => toast.error('Unable to start or resume the simulation.') })
  const action = useMutation({ mutationFn: ({ channel, target, content, actionType }: { channel: Channel; target: string; content: string; actionType: string }) => submitExecutionAction(execution!.execution_id, { action_type: actionType, actor_id: actorId, payload: { channel, content, to: target, document_id: channel === 'document' ? target : undefined } }), onSuccess: (result) => { setExecution(result); client.invalidateQueries({ queryKey: ['session', result.session_id] }); toast.success('Workflow action submitted.') }, onError: () => toast.error('Action was rejected. Check the requested channel and target.') })
  const workflow = versions.data?.find((item) => item.workflow_version_id === versionId)
  const elapsed = execution ? new Intl.DateTimeFormat(undefined, { timeStyle: 'medium' }).format(new Date()) : '—'
  function begin(event: FormEvent) { event.preventDefault(); start.mutate({ workflow_version_id: versionId, participant_id: participantId.trim(), context: { actor_id: actorId } }) }
  function send(channel: Channel, event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const actionType = channel === 'chat' ? 'reply_chat' : channel === 'email' ? 'reply_email' : channel === 'call' ? 'finish_call' : 'close_document'; action.mutate({ channel, target: String(data.get('target') ?? ''), content: String(data.get('content') ?? ''), actionType }); event.currentTarget.reset() }

  if (!execution) return <main className="runner-page"><header><div><p className="eyebrow">Simulation cockpit</p><h1>Start a guided run</h1><p>Select a participant actor and workflow, then enter the participant ID to start or resume a simulation.</p></div></header><form className="runner-start" onSubmit={begin}><label>Participant actor<select required value={actorId} onChange={(event) => setActorId(event.target.value)}><option value="">Select actor</option>{actors.data?.map((actor) => <option key={String(actor.actor_id)} value={String(actor.actor_id)}>{String(actor.actor_name)}</option>)}</select></label><label>Participant ID<input required value={participantId} placeholder="e.g. participant-123" onChange={(event) => setParticipantId(event.target.value)} /></label><label>Workflow version<select required value={versionId} onChange={(event) => setVersionId(event.target.value)}><option value="">Select workflow</option>{versions.data?.map((item) => <option key={item.workflow_version_id} value={item.workflow_version_id}>{item.workflow_name} · v{item.version_number}</option>)}</select></label><button disabled={!actorId || !participantId.trim() || !versionId || start.isPending}>{start.isPending ? 'Checking simulation…' : 'Start or resume simulation'}</button>{start.isError && <ErrorState message="Unable to start or resume the simulation." />}</form>{versions.isPending && <LoadingState />}</main>

  return <main className="runner-page cockpit"><header className="cockpit-header"><div><p className="eyebrow">Simulation cockpit</p><h1>{workflow?.workflow_name ?? 'Active simulation'}</h1><span>Version {workflow?.version_number ?? '—'} · Session {execution.session_id}</span></div><div className="cockpit-metrics"><div><UserRound size={15} /><small>Participant</small><strong>{participantId}</strong></div><div><Clock3 size={15} /><small>Elapsed</small><strong>{elapsed}</strong></div><div><small>Execution</small><StatusBadge status={execution.status} /></div></div></header>{execution.status === 'waiting' && <section className="waiting-banner"><Clock3 size={20} /><div><strong>Participant action required</strong><span>Reply on the requested channel with the selected target. Previous actions that do not match the workflow transition will be rejected.</span></div><StatusBadge status="waiting" /></section>}<section className="channel-workspace">{channels.map((channel) => <ChannelCard key={channel} channel={channel} events={(session.data?.[eventLists[channel]] ?? []) as SessionChannelEvent[]} actors={actors.data ?? []} documents={documents.data ?? []} disabled={action.isPending || execution.status === 'completed'} onSubmit={(event) => send(channel, event)} />)}</section></main>
}

function ChannelCard({ channel, events, actors, documents, disabled, onSubmit }: { channel: Channel; events: SessionChannelEvent[]; actors: Record<string, unknown>[]; documents: Record<string, unknown>[]; disabled: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  const Icon = channel === 'chat' ? MessageSquare : channel === 'email' ? Mail : channel === 'call' ? Phone : FileText
  const targets = channel === 'document' ? documents.map((item) => [String(item.document_id), String(item.document_name)]) : actors.map((item) => [String(item.actor_id), String(item.actor_name)])
  return <section className={`channel-card cockpit-card ${channel}`}><header><span className="channel-icon"><Icon size={17} /></span><div><h2>{channel}</h2><small>{events.length} event{events.length === 1 ? '' : 's'}</small></div></header><div className="channel-feed">{events.length ? events.map((item, index) => <article className={String(item.actor ?? item.from) === 'participant' ? 'participant' : ''} key={index}><span className="event-avatar">{String(item.actor ?? item.from ?? 'S').slice(0, 1).toUpperCase()}</span><div><small>{String(item.actor ?? item.from ?? 'system')} · {formatTime(item.timestamp)}</small><strong>{String(item.subject ?? item.document_name ?? item.call_id ?? item.chat_id ?? `${channel} activity`)}</strong><p>{String(item.content ?? item.action_type ?? '')}</p><em>{channel === 'chat' ? 'Read' : channel === 'document' ? 'Read-only state' : channel === 'call' ? 'Call event' : 'Inbox item'}</em></div></article>) : <p className="empty-channel">No {channel} activity yet.</p>}</div><form className="action-composer" onSubmit={onSubmit}><label>{channel === 'document' ? 'Document' : 'Recipient'}<select name="target" required>{targets.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>{channel !== 'document' && <label>{channel === 'email' ? 'Email body' : channel === 'call' ? 'Call note' : 'Message'}<textarea name="content" required placeholder={channel === 'email' ? 'Write a reply…' : 'Enter your response…'} /></label>}{channel === 'document' && <label className="read-only"><input type="checkbox" name="read-only" /> Open as read-only</label>}<button disabled={disabled}><Send size={15} />{channel === 'chat' ? 'Send chat reply' : channel === 'email' ? 'Send email reply' : channel === 'call' ? 'Finish call' : 'Close document'}</button></form></section>
}

function formatTime(value: unknown) { return typeof value === 'string' ? new Date(value).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : 'Just now' }
