import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useMemo, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { startExecution, submitExecutionAction } from '../../shared/api/executions'
import { getMasterData } from '../../shared/api/master-data'
import { getSession, type SessionChannelEvent } from '../../shared/api/sessions'
import { getPublishedVersions } from '../../shared/api/workflows'
import { ErrorState, LoadingState } from '../../shared/components/async-state'
import type { Execution } from '../../shared/types/workflow'

type Channel = 'chat' | 'email' | 'call' | 'document'
const channels: Channel[] = ['chat', 'email', 'call', 'document']
const eventLists: Record<Channel, keyof Pick<Awaited<ReturnType<typeof getSession>>, 'chat_inbox' | 'email_inbox' | 'call_state' | 'document_state'>> = { chat: 'chat_inbox', email: 'email_inbox', call: 'call_state', document: 'document_state' }

export function SimulationRunnerPage() {
  const client = useQueryClient(); const [participantId, setParticipantId] = useState('demo-participant'); const [versionId, setVersionId] = useState(''); const [execution, setExecution] = useState<Execution | null>(null)
  const versions = useQuery({ queryKey: ['published-versions'], queryFn: getPublishedVersions }); const actors = useQuery({ queryKey: ['master', 'actors'], queryFn: () => getMasterData('actors') }); const documents = useQuery({ queryKey: ['master', 'documents'], queryFn: () => getMasterData('documents') })
  const session = useQuery({ queryKey: ['session', execution?.session_id], queryFn: () => getSession(execution!.session_id!), enabled: Boolean(execution?.session_id), refetchInterval: execution?.status === 'waiting' || execution?.status === 'running' ? 2_000 : false })
  const start = useMutation({ mutationFn: startExecution, onSuccess: (result) => { setExecution(result); client.invalidateQueries({ queryKey: ['session', result.session_id] }) } })
  const action = useMutation({ mutationFn: ({ channel, target, content, actionType }: { channel: Channel; target: string; content: string; actionType: string }) => submitExecutionAction(execution!.execution_id, { action_type: actionType, actor_id: participantId, payload: { channel, content, to: target, document_id: channel === 'document' ? target : undefined } }), onSuccess: (result) => { setExecution(result); client.invalidateQueries({ queryKey: ['session', result.session_id] }) } })
  const groups = useMemo(() => { const map = new Map<string, typeof versions.data>(); for (const item of versions.data ?? []) map.set(item.workflow_name, [...(map.get(item.workflow_name) ?? []), item]); return [...map] }, [versions.data])
  function begin(event: FormEvent) { event.preventDefault(); start.mutate({ workflow_version_id: versionId, participant_id: participantId, context: {} }) }
  function send(channel: Channel, event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); action.mutate({ channel, target: String(data.get('target') ?? ''), content: String(data.get('content') ?? ''), actionType: channel === 'chat' ? 'reply_chat' : channel === 'email' ? 'reply_email' : channel === 'call' ? 'finish_call' : 'close_document' }); event.currentTarget.reset() }
  return <main className="runner-page"><header><div><h1>Simulation Runner</h1><p>Choose a channel and interact as the participant.</p></div><Link to="/studio">Open Studio</Link></header>{!execution ? <form className="runner-start" onSubmit={begin}><label>Participant / actor<select value={participantId} onChange={(event) => setParticipantId(event.target.value)}>{actors.data?.map((actor) => <option key={String(actor.actor_id)} value={String(actor.actor_id)}>{String(actor.actor_name)} · {String(actor.actor_id)}</option>)}</select></label><label>Published workflow<select required value={versionId} onChange={(event) => setVersionId(event.target.value)}><option value="">Select workflow</option>{groups.map(([name, items]) => <optgroup key={name} label={name}>{items?.map((item) => <option key={item.workflow_version_id} value={item.workflow_version_id}>v{item.version_number} · {item.workflow_version_id}</option>)}</optgroup>)}</select></label><button disabled={!versionId || start.isPending}>Start simulation</button>{start.isError && <ErrorState message="Unable to start simulation." />}</form> : <><section className="runner-status"><strong>{execution.status === 'waiting' ? 'Waiting for your action' : execution.status}</strong><span>Actor: {participantId}</span><span>Session: {execution.session_id}</span></section><section className="channel-workspace">{channels.map((channel) => <ChannelCard key={channel} channel={channel} events={(session.data?.[eventLists[channel]] ?? []) as SessionChannelEvent[]} actors={actors.data ?? []} documents={documents.data ?? []} disabled={action.isPending || execution.status === 'completed'} onSubmit={(event) => send(channel, event)} />)}</section></>}{versions.isPending && <LoadingState />}</main>
}

function ChannelCard({ channel, events, actors, documents, disabled, onSubmit }: { channel: Channel; events: SessionChannelEvent[]; actors: Record<string, unknown>[]; documents: Record<string, unknown>[]; disabled: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  const targetItems = channel === 'document' ? documents.map((item) => [String(item.document_id), String(item.document_name)]) : actors.map((item) => [String(item.actor_id), String(item.actor_name)])
  return <section className={`channel-card ${channel}`}><h2>{channel}</h2><div className="channel-feed">{events.length ? events.map((item, index) => <article key={index}><small>{String(item.actor ?? item.from ?? 'system')} · {formatTime(item.timestamp)}</small><strong>{String(item.subject ?? item.document_name ?? item.call_id ?? item.chat_id ?? '')}</strong><p>{String(item.content ?? item.action_type ?? '')}</p></article>) : <p>No activity yet.</p>}</div><form onSubmit={onSubmit}><label>{channel === 'document' ? 'Document' : 'Actor'}<select name="target" required>{targetItems.map(([id, name]) => <option key={id} value={id}>{name} · {id}</option>)}</select></label>{channel !== 'document' && <label>{channel === 'email' ? 'Email reply' : channel === 'chat' ? 'Message' : 'Call note'}<textarea name="content" required /></label>}<button disabled={disabled}>{channel === 'document' ? 'Close document' : channel === 'call' ? 'Finish call' : channel === 'email' ? 'Send email action' : 'Send chat action'}</button></form></section>
}
function formatTime(value: unknown) { return typeof value === 'string' ? new Date(value).toLocaleString() : '—' }
